In [1]:
import pandas as pd
import numpy as np

df = pd.read_csv("../data/raw/data.csv") # change path if needed
df.head()

,Booking ID,Payment Status,Address ID,Address Type,Area,City,State,Country,Lat,Long
0,509103,refunded_full,152622,Home,byalalu village chunchanaguppe post,Bengaluru,Karnataka,India,12.897291,77.375508
1,700991,refunded_full,208569,Farmhouse,Outside Hyderabad,Hyderabad,Telangana,India,16.969071,78.518297
2,717282,refunded_full,216864,Office,"Aawasari Phata Manchar, Taluka Ambegaon, Mahar...",Pune,Maharashtra,India,18.979685,73.947376
3,717285,refunded_full,216864,Office,"Aawasari Phata Manchar, Taluka Ambegaon, Mahar...",Pune,Maharashtra,India,18.979685,73.947376
4,717290,refunded_full,216864,Office,"Aawasari Phata Manchar, Taluka Ambegaon, Mahar...",Pune,Maharashtra,India,18.979685,73.947376

In [2]:
df.shape

(557, 10)

In [3]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 557 entries, 0 to 556
Data columns (total 10 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   Booking ID      557 non-null    int64
 1   Payment Status  557 non-null    str
 2   Address ID      557 non-null    int64
 3   Address Type    551 non-null    str
 4   Area            548 non-null    str
 5   City            557 non-null    str
 6   State           557 non-null    str
 7   Country         557 non-null    str
 8   Lat             546 non-null    float64
 9   Long            546 non-null    float64
dtypes: float64(2), int64(2), str(6)
memory usage: 43.6 KB

In [4]:
df.isnull().sum()

Booking ID         0
Payment Status     0
Address ID         0
Address Type       6
Area               9
City               0
State              0
Country            0
Lat               11
Long              11
dtype: int64

In [5]:
df.isnull().value_counts()

Booking ID  Payment Status  Address ID  Address Type  Area   City   State  Country  Lat    Long
False       False           False       False         False  False  False  False    False  False    544
                                        True          True   False  False  False    True   True       5
                                        False         False  False  False  False    True   True       3
                                                      True   False  False  False    True   True       2
                                                                                    False  False      2
                                        True          False  False  False  False    True   True       1
Name: count, dtype: int64

In [6]:
df.isnull().sum()

Booking ID         0
Payment Status     0
Address ID         0
Address Type       6
Area               9
City               0
State              0
Country            0
Lat               11
Long              11
dtype: int64

Dropping the lat and log  557-546

In [7]:
df = df.dropna(subset=["Lat", "Long"])

In [8]:
df.shape

(546, 10)

In [9]:
df["Area"].fillna("Unknown", inplace=True)

C:\Users\HP\AppData\Local\Temp\ipykernel_19580\1359495798.py:1: ChainedAssignmentError: A value is being set on a copy of a DataFrame or Series through chained assignment using an inplace method.
Such inplace method never works to update the original DataFrame or Series, because the intermediate object on which we are setting values always behaves as a copy (due to Copy-on-Write).

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' instead, to perform the operation inplace on the original object, or try to avoid an inplace operation using 'df[col] = df[col].method(value)'.

See the documentation for a more detailed explanation: https://pandas.pydata.org/pandas-docs/stable/user_guide/copy_on_write.html
  df["Area"].fillna("Unknown", inplace=True)

0                    byalalu village chunchanaguppe post
1                                      Outside Hyderabad
2      Aawasari Phata Manchar, Taluka Ambegaon, Mahar...
3      Aawasari Phata Manchar, Taluka Ambegaon, Mahar...
4      Aawasari Phata Manchar, Taluka Ambegaon, Mahar...
                             ...
552                                          Papdi talav
553                                      Kousalya colony
554                       Sector - 23, Ulwe, Navi Mumbai
555                                              Tower 2
556                     Jyothi Nagar, Bengaluru, Nagarur
Name: Area, Length: 546, dtype: str

In [10]:
df["Address Type"].fillna("Others", inplace=True)

C:\Users\HP\AppData\Local\Temp\ipykernel_19580\832634771.py:1: ChainedAssignmentError: A value is being set on a copy of a DataFrame or Series through chained assignment using an inplace method.
Such inplace method never works to update the original DataFrame or Series, because the intermediate object on which we are setting values always behaves as a copy (due to Copy-on-Write).

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' instead, to perform the operation inplace on the original object, or try to avoid an inplace operation using 'df[col] = df[col].method(value)'.

See the documentation for a more detailed explanation: https://pandas.pydata.org/pandas-docs/stable/user_guide/copy_on_write.html
  df["Address Type"].fillna("Others", inplace=True)

0           Home
1      Farmhouse
2         Office
3         Office
4         Office
         ...
552         Home
553         Home
554         Home
555         Home
556         Home
Name: Address Type, Length: 546, dtype: str

In [11]:
df.isnull().sum()

Booking ID        0
Payment Status    0
Address ID        0
Address Type      0
Area              2
City              0
State             0
Country           0
Lat               0
Long              0
dtype: int64

In [12]:
import numpy as np

df["Area"] = df["Area"].replace(["", " ", "NA", "null"], np.nan)

df["Area"].fillna("Unknown", inplace=True)

C:\Users\HP\AppData\Local\Temp\ipykernel_19580\2753948655.py:5: ChainedAssignmentError: A value is being set on a copy of a DataFrame or Series through chained assignment using an inplace method.
Such inplace method never works to update the original DataFrame or Series, because the intermediate object on which we are setting values always behaves as a copy (due to Copy-on-Write).

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' instead, to perform the operation inplace on the original object, or try to avoid an inplace operation using 'df[col] = df[col].method(value)'.

See the documentation for a more detailed explanation: https://pandas.pydata.org/pandas-docs/stable/user_guide/copy_on_write.html
  df["Area"].fillna("Unknown", inplace=True)

0                    byalalu village chunchanaguppe post
1                                      Outside Hyderabad
2      Aawasari Phata Manchar, Taluka Ambegaon, Mahar...
3      Aawasari Phata Manchar, Taluka Ambegaon, Mahar...
4      Aawasari Phata Manchar, Taluka Ambegaon, Mahar...
                             ...
552                                          Papdi talav
553                                      Kousalya colony
554                       Sector - 23, Ulwe, Navi Mumbai
555                                              Tower 2
556                     Jyothi Nagar, Bengaluru, Nagarur
Name: Area, Length: 546, dtype: str

In [13]:
df.isnull().sum()

Booking ID        0
Payment Status    0
Address ID        0
Address Type      0
Area              2
City              0
State             0
Country           0
Lat               0
Long              0
dtype: int64

In [14]:
df[df["Area"].isnull()]

,Booking ID,Payment Status,Address ID,Address Type,Area,City,State,Country,Lat,Long
467,2109044,refunded_full,611895,Home,NaN,Ahmedabad,Gujarat,India,23.10671,72.497739
468,2109045,refunded_full,611895,Home,NaN,Ahmedabad,Gujarat,India,23.10671,72.497739

In [15]:
df["Area"] = df.groupby("City")["Area"].transform(
    lambda x: x.fillna(x.mode()[0] if not x.mode().empty else "Unknown")
)

In [16]:
df.isnull().sum()

Booking ID        0
Payment Status    0
Address ID        0
Address Type      0
Area              0
City              0
State             0
Country           0
Lat               0
Long              0
dtype: int64

In [17]:
df.columns = df.columns.str.strip().str.lower().str.replace(" ", "_")
df.columns

Index(['booking_id', 'payment_status', 'address_id', 'address_type', 'area',
       'city', 'state', 'country', 'lat', 'long'],
      dtype='str')

In [18]:
df.duplicated().sum()

np.int64(0)

Standardize city names

Fixes:

"bengaluru", "Bangalore", "BENGALURU"

(Optional manual mapping if needed)

In [19]:
df["city"] = df["city"].str.strip().str.title()

In [20]:
df["area"] = df["area"].str.lower().str.strip().str.replace(r"\s+", " ", regex=True)

In [21]:
df.head(2)

,booking_id,payment_status,address_id,address_type,area,city,state,country,lat,long
0,509103,refunded_full,152622,Home,byalalu village chunchanaguppe post,Bengaluru,Karnataka,India,12.897291,77.375508
1,700991,refunded_full,208569,Farmhouse,outside hyderabad,Hyderabad,Telangana,India,16.969071,78.518297

In [22]:
# //Extract Pincode

import re

def extract_pincode(area):
    match = re.search(r"\b\d{6}\b", str(area))
    return match.group(0) if match else None

df["pincode"] = df["area"].apply(extract_pincode)

In [23]:
df["pincode"].value_counts().head()

pincode
382722    9
412115    4
603112    3
562106    3
382213    3
Name: count, dtype: int64

In [24]:
df["pincode"].value_counts()

pincode
382722    9
412115    4
603112    3
562106    3
382213    3
         ..
560049    1
412101    1
302017    1
500090    1
602024    1
Name: count, Length: 67, dtype: int64

In [25]:
# Pincode extraction from address yielded limited results due to inconsistent address formats.

# Therefore, latitude and longitude were used as the primary features for spatial analysis, 
# as they provide more complete and reliable location information.



df.head()

,booking_id,payment_status,address_id,address_type,area,city,state,country,lat,long,pincode
0,509103,refunded_full,152622,Home,byalalu village chunchanaguppe post,Bengaluru,Karnataka,India,12.897291,77.375508,NaN
1,700991,refunded_full,208569,Farmhouse,outside hyderabad,Hyderabad,Telangana,India,16.969071,78.518297,NaN
2,717282,refunded_full,216864,Office,"aawasari phata manchar, taluka ambegaon, mahar...",Pune,Maharashtra,India,18.979685,73.947376,NaN
3,717285,refunded_full,216864,Office,"aawasari phata manchar, taluka ambegaon, mahar...",Pune,Maharashtra,India,18.979685,73.947376,NaN
4,717290,refunded_full,216864,Office,"aawasari phata manchar, taluka ambegaon, mahar...",Pune,Maharashtra,India,18.979685,73.947376,NaN

In [26]:
df["lat"] = pd.to_numeric(df["lat"], errors="coerce")
df["long"] = pd.to_numeric(df["long"], errors="coerce")

In [27]:
df.head()

,booking_id,payment_status,address_id,address_type,area,city,state,country,lat,long,pincode
0,509103,refunded_full,152622,Home,byalalu village chunchanaguppe post,Bengaluru,Karnataka,India,12.897291,77.375508,NaN
1,700991,refunded_full,208569,Farmhouse,outside hyderabad,Hyderabad,Telangana,India,16.969071,78.518297,NaN
2,717282,refunded_full,216864,Office,"aawasari phata manchar, taluka ambegaon, mahar...",Pune,Maharashtra,India,18.979685,73.947376,NaN
3,717285,refunded_full,216864,Office,"aawasari phata manchar, taluka ambegaon, mahar...",Pune,Maharashtra,India,18.979685,73.947376,NaN
4,717290,refunded_full,216864,Office,"aawasari phata manchar, taluka ambegaon, mahar...",Pune,Maharashtra,India,18.979685,73.947376,NaN

In [28]:
df.isnull().sum()

booking_id          0
payment_status      0
address_id          0
address_type        0
area                0
city                0
state               0
country             0
lat                 0
long                0
pincode           450
dtype: int64

In [29]:
df.shape

(546, 11)

In [30]:
# Remove Invalid Coordinates

# India roughly lies within:

# Latitude: 6 to 38
# Longitude: 68 to 98

df = df[(df["lat"] >= 6) & (df["lat"] <= 38)]
df = df[(df["long"] >= 68) & (df["long"] <= 98)]

In [31]:
df.shape

(546, 11)

In [32]:
df.to_csv("../data/processed/cleaned_data.csv", index=False)